### ISSUE TITLE
Instalação da extensão no Firefox não funciona mais

### ISSUE THREAD

**Issue by goco-motta** [LacunaSoftware/docs#14]
O XPI entregue na [documentação](https://docs.lacunasoftware.com/pt-br/articles/web-pki/installation-webpki-gpo.html) não é compatível com o Firefox atualmente (109.0). Uma tentativa de instalação manual acusa um risco de segurança ou instabilidade.

O [instalador automático pelo site](https://get.webpkiplugin.com/Setup?brand=pbh&jslib=2.5.0&browser=Firefox&returnUrl=https%3A%2F%2Fbhissdigital.pbh.gov.br%2Fnfse%2Fpages%2Fsecurity%2FgeracaoNFS-e.jsf) também não funciona mais. Uma busca rápida mostra que o problema está sendo [reproduzido por outros usuários também](https://github.com/SeleniumHQ/selenium/issues/10910)

**Comment by brunocapu** [comment]
Olá @goco-motta 
> O XPI entregue na [documentação](https://docs.lacunasoftware.com/pt-br/articles/web-pki/installation-webpki-gpo.html) não é compatível com o Firefox atualmente (109.0).

Obrigado pelo alerta. Já atualizamos o ZIP na documentação com as versões mais recentes das web-extensions: [webpki-ext-2.16.0.zip](https://cdn.lacunasoftware.com/webpki/webpki-ext-2.16.0.zip)

> O [instalador automático pelo site](https://get.webpkiplugin.com/Setup?brand=pbh&jslib=2.5.0&browser=Firefox&returnUrl=https%3A%2F%2Fbhissdigital.pbh.gov.br%2Fnfse%2Fpages%2Fsecurity%2FgeracaoNFS-e.jsf) também não funciona mais.

Na verdade a instalação automática via setup-site continua funcionando normalmente. A última atualização feita na web-extension para Firefox foi em 2022/06/06
![image](https://user-images.githubusercontent.com/3412136/210366513-b1194342-2fe6-4f92-871b-b67f1cb778f4.png)
Pode ter havido alguma instabilidade no seu Firefox ou na validação na Mozilla. Por favor teste novamente a instalação.
à disposição.

**Comment by goco-motta** [comment]
Obrigada! Ambos funcionaram agora :)
