### ISSUE TITLE
Documentação sobre browsers não suportados

### ISSUE THREAD

**Issue by alfredmyers** [LacunaSoftware/docs#2]
No documento [Browsers suportados](https://github.com/LacunaSoftware/docs/blob/master/docs.pt-br/articles/web-pki/browser-support.md) é dito:

> Embora a Microsoft tenha adicionado suporte a extensões Edge, nem todas as APIs necessárias foram implementadas. Especificamente uma API crítica para o funcionamento do Web PKI chamada de **native messaging ainda não está disponível**, ...

No entanto, o documento [Native messaging in Microsoft Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging) dá a entender que a API de native messaging é suportada sim.

Alguma mudança em relação aos browsers suportados?

**Comment by alexswi** [comment]
Alfred,

Já estamos trabalhando na versão Edge e deve estar disponível até o final de abril. 

Obrigado por apontar o erro na nossa documentação.
