### ISSUE TITLE
Documentação de instalação no Mac OS

### ISSUE THREAD

**Issue by adolfobrunno** [LacunaSoftware/docs#4]
Olá, amigos. Vocês possuem alguma documentação de instalação no Mac OS? Na página [de documentação](https://docs.lacunasoftware.com/pt-br/articles/pki-express/setup/index.html) só tem instruções para Linux e Windows, mas vi no link de versões suportadas que está listado o Mac OS X.

**Comment by leopignataro** [comment]
Olá, @adolfobrunno !

O PKI Express é um módulo que deve ser instalado apenas *no servidor* onde está a sua aplicação web. Ele só suporta servidores Windows e Linux.

Entretanto, se você estiver se referindo à instalação em Mac OS do [Web PKI](https://docs.lacunasoftware.com/pt-br/articles/web-pki/index.html), componente de assinatura digital que os *usuários finais* instalam, esse sim, naturalmente, é [suportado em Mac OS](https://docs.lacunasoftware.com/pt-br/articles/web-pki/browser-support.html).
